export enum FriendEvents {
  FRIEND_INVITATION = 'FRIEND_INVITATION',
  FRIEND_STATUS_CHANGE = 'FRIEND_STATUS_CHANGE',
  FRIEND_REMOVE = 'FRIEND_REMOVE',
  FRIEND_ONLINE_LIST = 'FRIEND_ONLINE_LIST',
  FRIEND_ONLINE = 'FRIEND_ONLINE',
  FRIEND_OFFLINE = 'FRIEND_OFFLINE',
}
