export enum WheelEvents {
  ROOM_JOIN = 'ROOM_JOIN',
  ROOM_UPDATE = 'ROOM_UPDATE',
  ROOM_LEAVE = 'ROOM_LEAVE',
  ROOM_INSERT_GAMES = 'ROOM_INSERT_GAMES',
  ROOM_REMOVE_GAMES = 'ROOM_REMOVE_GAMES',
}
